version: '3'
services:
  front:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/share/nginx/html
  back:
    image: python:3.9
    ports:
      - "8000:8000"
    volumes:
      - ./back:/usr/src/app
    working_dir: /usr/src/app
    command: /usr/src/app/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
